# Developed by Eng Mouaz M. AlShahmeh
name: supabase_example
description: Developed by Eng Mouaz M. AlShahmeh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase: ^0.3.5 # add this line with latest version
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
